use_frameworks!

target 'RestorableUIControl_Example' do
  pod 'RestorableUIControl', :path => '../'

  target 'RestorableUIControl_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0.0'
    pod 'Nimble', '~> 8.0.1'
  end
end
